
jwt:
  signing-key: 'jwtSecret'
  expires-time: 604800
  buffer-time: 86400

zap:
  level: 'info'
  format: 'json'
  prefix: ''
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false

redis:
  db: 0
  addr: '172.21.0.2:6379'
  password: '123456'

email:
  to: 'xxx@qq.com'
  port: 25
  from: '1124938791@qq.com'
  host: 'smtp.qq.com'
  is-ssl: false
  secret: 'bvewllmttezxjehi'
  nickname: 'test'


casbin:
  model-path: './rbac_model.conf'

jaeger:
  name: 'go-layout'
  host: '172.21.0.2:6831'

system:
  name: 'go-layout'
  port: 8888
  db-type: 'mysql'
  gin-mode: 'test'   #debug、release、test
  rate: 2

captcha:
  key-long: 6
  img-width: 240
  img-height: 80


mysql:
  path: '172.21.0.2:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'go-layout'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: true

kafka:
  address: '172.21.0.2:9092'
  topics: 'warn'


es:
  path: 'http://172.21.0.2:9200'
  username: 'elastic'
  password: '1qaz!QAZ'
